version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tpfoyer
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .  # si tu buildes localement, sinon commente cette ligne
    image: 172.27.245.210:8083/springboot-foyer:3.0.0
    container_name: springboot-app
    restart: always
    depends_on:
      - db
    ports:
      - "9097:8089"  # HostPort:ContainerPort
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tpfoyer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SERVER_SERVLET_CONTEXT_PATH: /foyer
      SERVER_PORT: 8089

volumes:
  postgres-data:
