services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
  
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
