version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: tpfoyer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    image: springboot-app:latest
    container_name: springboot-app
    restart: always
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tpfoyer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SERVER_SERVLET_CONTEXT_PATH: /foyer
      SERVER_PORT: 8089

volumes:
  postgres-data:
